version: "3.0"

services:
  my-app:
    container_name: ${CONTAINER_NAME}
    build: "./"
    ports:
      - "${PORT}:${PORT}"
    security_opt:
      - "seccomp:unconfined"
    tty: true
    stdin_open: true
    command: dlv debug --headless --listen=:${PORT} --api-version=2 --log ${MAIN_FILE}
